{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "colab_type": "text",
        "id": "view-in-github"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/fduartej/python_covid_trabajo_final/blob/main/CovidNotebook.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 302
        },
        "id": "vGkWyj2E7sIj",
        "outputId": "cd4fb07c-7472-4ca7-8fb4-3e334414412a"
      },
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>id_centro_vacunacion</th>\n",
              "      <th>id_ubigeo</th>\n",
              "      <th>nombre</th>\n",
              "      <th>latitud</th>\n",
              "      <th>longitud</th>\n",
              "      <th>entidad_administra</th>\n",
              "      <th>id_eess</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>557</td>\n",
              "      <td>993</td>\n",
              "      <td>Estacionamiento Del Centro Comercial \"el Quind...</td>\n",
              "      <td>-14.074283</td>\n",
              "      <td>-75.739709</td>\n",
              "      <td>C.S. LOS AQUIJES</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>558</td>\n",
              "      <td>993</td>\n",
              "      <td>Estacionamiento Del Centro Comercial Plaza Sol</td>\n",
              "      <td>-14.069467</td>\n",
              "      <td>-75.727896</td>\n",
              "      <td>C.S. LA PALMA</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>559</td>\n",
              "      <td>995</td>\n",
              "      <td>Ie 22511</td>\n",
              "      <td>-14.114718</td>\n",
              "      <td>-75.675898</td>\n",
              "      <td>C.S. LOS AQUIJES</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>560</td>\n",
              "      <td>998</td>\n",
              "      <td>Ie. Victor Manuel Maurtua</td>\n",
              "      <td>-14.048166</td>\n",
              "      <td>-75.707636</td>\n",
              "      <td>C.S. PARCONA</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>561</td>\n",
              "      <td>1000</td>\n",
              "      <td>Primera Loza De La Expansión Urbana</td>\n",
              "      <td>-13.969434</td>\n",
              "      <td>-75.772475</td>\n",
              "      <td>C.S. SAN JUAN BAUTISTA</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "   id_centro_vacunacion  id_ubigeo  \\\n",
              "0                   557        993   \n",
              "1                   558        993   \n",
              "2                   559        995   \n",
              "3                   560        998   \n",
              "4                   561       1000   \n",
              "\n",
              "                                              nombre    latitud   longitud  \\\n",
              "0  Estacionamiento Del Centro Comercial \"el Quind... -14.074283 -75.739709   \n",
              "1     Estacionamiento Del Centro Comercial Plaza Sol -14.069467 -75.727896   \n",
              "2                                           Ie 22511 -14.114718 -75.675898   \n",
              "3                          Ie. Victor Manuel Maurtua -14.048166 -75.707636   \n",
              "4                Primera Loza De La Expansión Urbana -13.969434 -75.772475   \n",
              "\n",
              "       entidad_administra  id_eess  \n",
              "0        C.S. LOS AQUIJES        0  \n",
              "1           C.S. LA PALMA        0  \n",
              "2        C.S. LOS AQUIJES        0  \n",
              "3            C.S. PARCONA        0  \n",
              "4  C.S. SAN JUAN BAUTISTA        0  "
            ]
          },
          "execution_count": 1,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "#Inicial\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import plotly.graph_objects as go\n",
        "\n",
        "\n",
        "centro_vacunacion = pd.read_csv('TB_CENTRO_VACUNACION.csv',delimiter=\",\")\n",
        "centro_vacunacion.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 357
        },
        "id": "hfJEpiJz-apO",
        "outputId": "362c33f8-c8d1-4566-fda7-ea1616d3c935"
      },
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>id_ubigeo</th>\n",
              "      <th>ubigeo_reniec</th>\n",
              "      <th>ubigeo_inei</th>\n",
              "      <th>departamento_inei</th>\n",
              "      <th>departamento</th>\n",
              "      <th>provincia_inei</th>\n",
              "      <th>provincia</th>\n",
              "      <th>distrito</th>\n",
              "      <th>region</th>\n",
              "      <th>macroregion_inei</th>\n",
              "      <th>macroregion_minsa</th>\n",
              "      <th>iso_3166_2</th>\n",
              "      <th>fips</th>\n",
              "      <th>superficie</th>\n",
              "      <th>altitud</th>\n",
              "      <th>latitud</th>\n",
              "      <th>longitud</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>10101.0</td>\n",
              "      <td>10101</td>\n",
              "      <td>1</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>101</td>\n",
              "      <td>CHACHAPOYAS</td>\n",
              "      <td>CHACHAPOYAS</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>ORIENTE</td>\n",
              "      <td>MACROREGION ORIENTE</td>\n",
              "      <td>PE-AMA</td>\n",
              "      <td>1</td>\n",
              "      <td>154.0</td>\n",
              "      <td>2338.0</td>\n",
              "      <td>-6.2294</td>\n",
              "      <td>-77.8728</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>10102.0</td>\n",
              "      <td>10102</td>\n",
              "      <td>1</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>101</td>\n",
              "      <td>CHACHAPOYAS</td>\n",
              "      <td>ASUNCION</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>ORIENTE</td>\n",
              "      <td>MACROREGION ORIENTE</td>\n",
              "      <td>PE-AMA</td>\n",
              "      <td>1</td>\n",
              "      <td>26.0</td>\n",
              "      <td>2823.0</td>\n",
              "      <td>-6.0325</td>\n",
              "      <td>-77.7108</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>10103.0</td>\n",
              "      <td>10103</td>\n",
              "      <td>1</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>101</td>\n",
              "      <td>CHACHAPOYAS</td>\n",
              "      <td>BALSAS</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>ORIENTE</td>\n",
              "      <td>MACROREGION ORIENTE</td>\n",
              "      <td>PE-AMA</td>\n",
              "      <td>1</td>\n",
              "      <td>357.0</td>\n",
              "      <td>859.0</td>\n",
              "      <td>-6.8358</td>\n",
              "      <td>-78.0197</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>4</td>\n",
              "      <td>10104.0</td>\n",
              "      <td>10104</td>\n",
              "      <td>1</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>101</td>\n",
              "      <td>CHACHAPOYAS</td>\n",
              "      <td>CHETO</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>ORIENTE</td>\n",
              "      <td>MACROREGION ORIENTE</td>\n",
              "      <td>PE-AMA</td>\n",
              "      <td>1</td>\n",
              "      <td>57.0</td>\n",
              "      <td>2143.0</td>\n",
              "      <td>-6.2556</td>\n",
              "      <td>-77.7008</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>5</td>\n",
              "      <td>10105.0</td>\n",
              "      <td>10105</td>\n",
              "      <td>1</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>101</td>\n",
              "      <td>CHACHAPOYAS</td>\n",
              "      <td>CHILIQUIN</td>\n",
              "      <td>AMAZONAS</td>\n",
              "      <td>ORIENTE</td>\n",
              "      <td>MACROREGION ORIENTE</td>\n",
              "      <td>PE-AMA</td>\n",
              "      <td>1</td>\n",
              "      <td>143.0</td>\n",
              "      <td>2677.0</td>\n",
              "      <td>-6.0783</td>\n",
              "      <td>-77.7375</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "   id_ubigeo  ubigeo_reniec  ubigeo_inei  departamento_inei departamento  \\\n",
              "0          1        10101.0        10101                  1     AMAZONAS   \n",
              "1          2        10102.0        10102                  1     AMAZONAS   \n",
              "2          3        10103.0        10103                  1     AMAZONAS   \n",
              "3          4        10104.0        10104                  1     AMAZONAS   \n",
              "4          5        10105.0        10105                  1     AMAZONAS   \n",
              "\n",
              "   provincia_inei    provincia     distrito    region macroregion_inei  \\\n",
              "0             101  CHACHAPOYAS  CHACHAPOYAS  AMAZONAS          ORIENTE   \n",
              "1             101  CHACHAPOYAS     ASUNCION  AMAZONAS          ORIENTE   \n",
              "2             101  CHACHAPOYAS       BALSAS  AMAZONAS          ORIENTE   \n",
              "3             101  CHACHAPOYAS        CHETO  AMAZONAS          ORIENTE   \n",
              "4             101  CHACHAPOYAS    CHILIQUIN  AMAZONAS          ORIENTE   \n",
              "\n",
              "     macroregion_minsa iso_3166_2  fips  superficie  altitud  latitud  \\\n",
              "0  MACROREGION ORIENTE     PE-AMA     1       154.0   2338.0  -6.2294   \n",
              "1  MACROREGION ORIENTE     PE-AMA     1        26.0   2823.0  -6.0325   \n",
              "2  MACROREGION ORIENTE     PE-AMA     1       357.0    859.0  -6.8358   \n",
              "3  MACROREGION ORIENTE     PE-AMA     1        57.0   2143.0  -6.2556   \n",
              "4  MACROREGION ORIENTE     PE-AMA     1       143.0   2677.0  -6.0783   \n",
              "\n",
              "   longitud  \n",
              "0  -77.8728  \n",
              "1  -77.7108  \n",
              "2  -78.0197  \n",
              "3  -77.7008  \n",
              "4  -77.7375  "
            ]
          },
          "execution_count": 2,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "ubigeo = pd.read_csv('TB_UBIGEOS.csv',delimiter=\",\")\n",
        "ubigeo.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {},
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "2022-12-17 17:23:55.289 INFO    matplotlib.font_manager: generated new fontManager\n",
            "2022-12-17 17:23:57.033 \n",
            "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
            "  command:\n",
            "\n",
            "    streamlit run c:\\Users\\Inteligo\\miniconda3\\envs\\trabajo_final\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
          ]
        }
      ],
      "source": [
        "import streamlit as st\n",
        "\n",
        "option = st.selectbox('Selecciona el departamento:',('AMAZONAS','ANCASH','APURIMAC','AREQUIPA','AYACUCHO','CAJAMARCA','CALLAO','CUSCO','HUANCAVELICA','HUANUCO','ICA','JUNIN','LA LIBERTAD','LAMBAYEQUE','LIMA','LORETO','MADRE DE DIOS','MOQUEGUA','PASCO','PIURA','PUNO','SAN MARTIN','TACNA','TUMBES','UCAYALI'))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {},
      "outputs": [],
      "source": [
        "st.write('Seleccionó:', option)\n"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "authorship_tag": "ABX9TyMyVV/R64srn9F0xeeVX2XI",
      "include_colab_link": true,
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3.7.15",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.7.15"
    },
    "vscode": {
      "interpreter": {
        "hash": "557c4add9d7379ad3ce8e517a2c16eab9553c196e788476e9b758ec6d02cc2aa"
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
